package imie.apiSalle.model;

public enum RoleUtilisateur {
    RESPONSABLE_GLOBAL_APPLICATION,
    RESPONSABLES_DE_GESTION,
    RESPONSABLES_PEDAGOGIQUES_DE_FORMATION,
    PROFS,
    RESPONSABLE_DE_MAINTENANCE,
    ETUDIANT;
}
